### ISSUE TITLE
Shadows on Safari - p5 tested

### ISSUE THREAD

**Issue by wagedu** [patriciogonzalezvivo/lygia#41]
Hi, 
this issue appears specifically on Safari on Mac, using the p5 example on 
https://editor.p5js.org/patriciogonzalezvivo/sketches/hwBn0i0qw
I don't know if it extends to other coding languages or OSs

I wouldn't know how to describe other than it works fine on Firefox and Chrome, but when run on Safari, the dragon seems to project its own silhouette on itself. As a solid shadow across its chest, on the front and back

Images 1 and 2 show the example run on Firefox and Chrome - working right

![FF-Chrome-Back](https://user-images.githubusercontent.com/1332848/213357875-98bf1e59-d1e8-4b3d-9a04-aefd8c488800.png)
![FF-Chrome-Front](https://user-images.githubusercontent.com/1332848/213357879-aa312d78-e718-471c-85b3-abb51cdfcf0b.png)

Images 3 and 4 show what happens when it's run on Safari - silhouetted shadow
![Safari-Back](https://user-images.githubusercontent.com/1332848/213357973-02605e7d-e439-4343-9c94-60305c025610.png)
![Safari-Front](https://user-images.githubusercontent.com/1332848/213357979-ee81c9bd-9e6d-4244-adb5-5ef6d590b289.png)

If there's an obvious solution that I clearly missed, please let me know :)

Thanks in advance

**Comment by wagedu** [comment]
Also, I'm sure this not the place but if I may... 
The original version of the example, at least when it was announced on Twitter, used to work with solid fills, there was no matcap. You probably won't remember, but you even helped me find a way to add my own shadow-casting objects
The current version, though, uses matcap and I can't figure out how to disable it and use my solid fill(s)/colors of choice. material.frag looks completely different.
I think this information may be interesting to more users, right?
Any tips, please? Thx

**Comment by patriciogonzalezvivo** [comment]
Hi @wagedu, Seams you were running the example `lygia_3D_sphereMap` instead of `lygia_3D_pbr_material` from the [sketches list](https://editor.p5js.org/patriciogonzalezvivo/sketches) 
About the weirdness on Firefox, I can reproduce the issue on my side (Ubuntu 22.04, AMD/Nvidia). But I'm pretty sure this is a P5js issue rather a LYGIA one. The right people to contact would be @qianqianye and @davepagurek 
![Screenshot from 2023-02-04 09-04-14](https://user-images.githubusercontent.com/346914/216772870-bce73060-f31c-44b0-8c62-e44e7538793f.png)
